### PR TITLE
96 gui interface

### PR DESCRIPTION
**Pull request by Yooply**
Mostly functional gui. Requires flask setup which should be achievable by doing `python3 -m pip install -r requirements.txt`. Only supports local server at this time. Needs comments/documentation and a few slight alterations.

### CODE REVIEW

**Comment by Yooply** [comment]
Functional gui that allows starting bot, stopping bot, and generating lead stats and casedist graphs. Currently only works on computer it is run on and is not ready for network deploy. It shouldn't cause and major issues however I did reorganize the graph generation code so let me know if any changes are necessary or if any cleanup is needed. Should be able to incrementally implement new features as smaller tickets moving forward.

**Comment by AndrewAlbizati** [comment]
Wow John! This GUI is incredible, much better than I was expecting. I like the nice stylization as well as the intuitive user interface. I added some things I found during my initial testing as well as testing on the bot computer.

For now, I'm going to keep the program running on the bot computer for beta bot to test the longevity of the program. It'll need to be able to run for weeks without any restarting.

Notes:
1. The `#!./.venv/bin/python3` file header in `start_local_server.py` causes problems when trying to run the program on Windows. 🙃
2. The dashboard website can actually be accessed from any device (as long as you're connected to the VPN or ethernet. There isn't any good way to prevent this, but I think some form of login page would help secure the website (maybe just having leads login using some admin account credentials that we come up with)
3. Let's remove the CSS wiki link (I saw in the code comments you were unsure whether or not to keep it)
4. I got this error message when I tried to quit the bot
```
127.0.0.1 - - [07/Dec/2023 18:11:23] "GET /static/dashboard.css HTTP/1.1" 304 -
received stop bot
[2023-12-07 18:11:25,049] ERROR in app: Exception on /stop_bot [GET]
Traceback (most recent call last):
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Helpdesk\Desktop\CaseClaim\web\gui.py", line 139, in stop_bot
    bot_running_status = controller.stop_bot()
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Helpdesk\Desktop\CaseClaim\web\controller.py", line 32, in stop_bot
    _bot_process.send_signal(signal.SIGINT)
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1618, in send_signal
    raise ValueError("Unsupported signal: {}".format(sig))
ValueError: Unsupported signal: 2
```

**Comment by Yooply** [comment]
@AndrewAlbizati I added user authentication via a password and flask sessions. I also think I fixed the windows signal issue and removed the bang line. In order to run the local server you will need to change the default password in `web/gui.py` after pulling and then run `python3 start_local_server.py` from the project root directory. Can you test on windows and if it works it should be good for merging unless there's any other issues.

**Comment by Yooply** [comment]
I made a few updates to the way the web server loads secrets. It now uses python-dotenv to use environment variables instead of hardcoding passwords so to run the code you need to create a `.env` file and add a `DISCORD_TOKEN` and a `PASSWORD` environment variable using the `KEY=value` format.

**Pull request closed without merging**
